# Generated by Django 5.2.2 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='facility_icons'),
        ),
        migrations.AlterField(
            model_name='locationimage',
            name='image',
            field=models.ImageField(upload_to='location_images'),
        ),
    ]
