# Generated by Django 5.2.2 on 2025-06-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_destination_schedule_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='rental_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
